# Generated by Django 4.1.1 on 2022-09-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenda', models.CharField(max_length=128)),
                ('talle', models.CharField(max_length=128)),
                ('precio', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=64)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMuniecos.marcas')),
            ],
        ),
        migrations.CreateModel(
            name='muniecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('munieco', models.CharField(max_length=128)),
                ('precio', models.CharField(max_length=128)),
                ('anio_fabricacion', models.DateTimeField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMuniecos.marcas')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMuniecos.origen')),
            ],
        ),
    ]
