# Generated by Django 4.1 on 2022-09-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMuniecos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marcas',
            new_name='Marca',
        ),
        migrations.RenameModel(
            old_name='muniecos',
            new_name='Munieco',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
