# Generated by Django 4.1 on 2022-09-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMuniecos', '0002_rename_marcas_marca_rename_muniecos_munieco_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
